### ISSUE TITLE
Accessing the Absinthe context within Authz

### ISSUE THREAD

**Issue by jgwmaxwell** [coryodaniel/speakeasy#4]
Hi there,

This project looks great, but I'm struggling to make it fit a specific use-case I have for it. Essentially authorization of a user for an activity depends on both the identity of the user, but also the (nice generic term) Context they are in. Would you be open to a PR that adds a arity-3 option to get_resource function that passes in the execution context itself, or maybe the entire speakeasy context so that could be decorated with additional data?

Thanks!

**Comment by jgwmaxwell** [comment]
Obviously that is incoherent - shouldn't write issues when I'm running for a train!

For clarity, I'm talking about `LoadResource` there and allowing resource loader functions to accept additional data to permit scoped loading rather than solely relying upon authz doing the right thing.

**Comment by coryodaniel** [comment]
Thanks for the PR! Sorry for the delay. Id been out of GraphQL land for a while
